[package]
name = "rwc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
unicode-segmentation = "1.12.0"

[[bin]]
name = "rwc"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"
